### ISSUE TITLE
もっと適切な日本語がありそう

### ISSUE THREAD

**Issue by Aseiide** [kotakawase/pomoru#120]
discordサーバーで活用させてもらっています。
動作としては満足しているのですが、もっと適した日本語がありそうだなと思ってissueを立てさせてもらいました。
![スクリーンショット 2022-05-04 17 22 41](https://user-images.githubusercontent.com/45246171/166646262-dee47590-472c-42bd-9522-1fa27a846c68.png)

`short breakを始めます` -> `ちょっと休憩しましょう！`
`pomodoroを始めます` -> `作業を開始しましょう！`
`longbreakを始めます` -> `気分をリフレッシュしましょう`

とかですかね〜。

もしよろしければご検討ください  :bowing_man:

**Comment by kotakawase** [comment]
ご活用していただきありがとうございます。

本件、僕も運用してみてメッセージが一部日本語じゃないことに違和感を感じていたりしていたので、登録してくださり助かりました。
いつ作業できるか確約できませんが、こちら対応させていただければと思います🙆‍♂️

また何か気になる点がございましたらお気軽にご連絡お待ちしております。
今後ともよろしくお願いいたします。

**Comment by kotakawase** [comment]
@Aseiide 
遅くなりましたが、こちら対応させていただきました〜！
デプロイまではお時間いただければと思います🙏
